# Generated by Django 4.2.6 on 2023-10-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletags_alter_article_options_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletags',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной раздел'),
        ),
    ]
